apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-depl
spec:
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: comments
          image: alexandraioan/recommendation-service
          ports:
            - containerPort: 8001
---

apiVersion: v1
kind: Service
metadata:
  name: recommendation-clusterip-srv
spec:
  type: LoadBalancer
  selector:
    app: recommendation
  ports:
    - name: recommendation
      protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendationsdb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationsdb
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 400Mi
